#logging:
#  level:
#    root: info
#    org:
#      springframework:
#        orm:
#          jpa: debug
#        transaction: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

application:
  security:
    authentication:
      jwt:
        secret-key: FJDO7OFJDO29DNNVYH8DQ92D9GNMV98U8D721HD87JNCM5R6Q2
        expire-time-in-minutes: 10000